name: Publish
on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm ci
      if: steps.node-cache.outputs.cache-hit != 'true'

    - name: Publish to npm
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm publish --tag ${{ github.event.release.prerelease && 'next' || 'latest' }}
